### PR TITLE
Commandline

### PR DESCRIPTION
**Pull request by FlorisCreyf**
I will need to resolve merge conflicts when the other branches are merged. In the meanwhile, this feature is finished.

### CODE REVIEW

**Comment by StructByLightning** [comment]
Shouldn't this be an NPM script? It doesn't look like you added it to package.json.

**Comment by FlorisCreyf** [comment]
Conflicts resolved.

**Comment by DanielBrewerPsu** [comment]
> Shouldn't this be an NPM script? It doesn't look like you added it to package.json.

Related to Raven's question, I wasn't sure how to execute it either, so I added a few things that might not be what we want:
- added references to yargs to package.json
- added comments showing how to launch this using "node cli.js --start-date 2020 etc etc"

If there's a better way to do this all, please overwrite those changes I made.

**Comment by FlorisCreyf** [comment]
The script is executed with node. I think it is pretty easy to use, especially when it throws error messages whenever you try to do something that does not make sense. You can't use the front-end without node either.

**Pull request merged**
